export default {
  TEXT: 'TEXT',
  MEDIA: 'MEDIA',
  MEDIA_IMAGE: 'IMAGE',
  MEDIA_AUDIO: 'AUDIO',
  MEDIA_VIDEO: 'VIDEO',
  CATEGORY: 'OPTION',
  API: 'API',
  LOOP: 'LOOP',
  GALLERY: 'GALLERY',
  JSON_API: 'JSON_API',
};
