export default {
  INTENTS: {
    INTENTS_TITLE: 'intents',
  },
  ACTIONS: {
    AUDIO: 'audio',
    VIDEO: 'video',
    NAME_OF_OPTION: 'Name of option',
    VALUE: 'Value',
  },
  SEARCH: 'Search',
  SEARCH_TRAINING_PHRASES: 'Search training phrases',
  ADD_USER_EXPRESSION: 'Add user expression',
  FETCH_DATA_FAILED: 'Fetch data failed',
  UPDATE_FAILED: 'Update failed',
  UPDATE_SUCCESS: 'Update success',
  CREATE_FAILED: 'Create failed',
  CREATE_SUCCESS: 'Create success',
  DELETE_FAILED: ' Delete failed',
  DELETE_SUCCESS: 'Delete success',
  ACTION_ASK_AGAIN: 'Action ask again',
  NUMBER_OF_LOOP: 'Number of loop',
  ACTION_BREAK: 'Action when too number loop',
  REGEX_FUNCTION: 'Regex Function',
  ADD: 'Add',
  DELETE: 'Delete',
  EDIT: 'Edit',
  ENTER_VALUE: 'Enter value',
  ENTER_SYNONYMS: 'Enter Synonyms',
  ENTER_TO_INPUT_OTHER_ENTITY: 'Enter @ to input other entity',
};
