version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PORT=${PORT}
      - REACT_APP_API_DOMAIN=${REACT_APP_API_DOMAIN}
      - REACT_APP_PORTAL_DOMAIN=${REACT_APP_PORTAL_DOMAIN}
      - REACT_APP_UPLOAD_FILE_DOMAIN=${REACT_APP_UPLOAD_FILE_DOMAIN}
